### ISSUE TITLE
Removing ad in the matchroom

### ISSUE THREAD

**Issue by trsted** [Maksim-Nikolaev/faceit-block-ad#1]
Hey, is it possible to expand this script to also remove the huge ad behind the matchroom window?

This may be a bit harder, since they seem to be backed into the same element. With ublock I can only remove it all together.
![image](https://github.com/Maksim-Nikolaev/faceit-block-ad/assets/168859002/c0eaa58b-ba23-4936-bd00-d0ce38e4b80e)

Removed with ublock:
![image](https://github.com/Maksim-Nikolaev/faceit-block-ad/assets/168859002/1ebaf13f-0a90-4593-a171-cade9fa03cf2)

**Comment by Maksim-Nikolaev** [comment]
Hey, the script is supposed to remove that part. 
Can you colaborate on it? I didn't see those ads recently and thought they removed it
For example: 
![image](https://github.com/Maksim-Nikolaev/faceit-block-ad/assets/45855362/135825e8-50e5-4119-9343-abe7ca64e0d0)

**Comment by trsted** [comment]
Hm, it seems the script doesn't work at all for me then. When accepting the match I also got an ad.

I am on LibreWolf 126.0-1 and use Violentmonkey 2.19.0. Script seems to be activated on faceit.com website.

![image](https://github.com/Maksim-Nikolaev/faceit-block-ad/assets/168859002/4bf42e85-65cf-469a-be17-2e3e0b2b2a16)

**Comment by trsted** [comment]
![image](https://github.com/Maksim-Nikolaev/faceit-block-ad/assets/168859002/c3431f17-5e1b-4e90-9ea8-0af9324ad4c2)
Here a screen from match accept :(

**Comment by Maksim-Nikolaev** [comment]
Add me on faceit/steam/discord so I can look up into the issue
Discord: .bronix
Faceit and Steam friend request sent

**Comment by trsted** [comment]
Hey again,
I am not sure what changed, but the script seems to fully work now.

Accept ads are gone and matchroom.

![image](https://github.com/Maksim-Nikolaev/faceit-block-ad/assets/168859002/40583042-b3b4-4671-9f4a-f33766d0b03d)

![image](https://github.com/Maksim-Nikolaev/faceit-block-ad/assets/168859002/23dc57ac-f3df-4717-a999-67f353e7549e)

Thanks for the help nonetheless
